Mejoras en el entendimiento, obtención de datos y cálculo de retorno de ganancias
enzosanchezc/haze pull request #16
Opened 2023-05-19 00:16 UTC by LucianoOrtega

Se implementaron mejoras en el proceso de obtención de datos, asegurando una correcta adquisición de la información necesaria. Se revisaron las solicitudes y se realizaron ajustes para obtener los datos de manera más precisa y confiable.

También se llevó a cabo una mejora en el cálculo de las ganancias. Se implementó un método más eficiente para determinar el retorno de las ganancias, teniendo en cuenta factores relevantes y realizando los cálculos correspondientes de forma más precisa.

2023-05-19 02:33 UTC, enzosanchezc requested changes
Hola, gracias por contribuir al repo! Tengo un par de comentarios respecto a los cambios:
1- Buenisimo lo de obtener los juegos sin necesidad de la webAPIKey. Es un paso menos que tiene que hacer el usuario.
2- No entendí la mejora en la obtención de la cantidad de cromos. La división con doble barra hace división entera y descarta el resto (redondea para abajo). La lógica actual funciona y es elegante.
3- Los cálculos de retornos tienen la constante 0.8696 porque es el porcentaje que se queda el usuario, el resto va para Steam. La idea es que el número que vemos en el excel es la plata final que vamos a obtener.

Por último, esto habría que mergearlo a dev. No se si se puede hacer desde acá o hay que hacer la pull request devuelta, nunca hice una

2023-05-19 17:36 UTC, LucianoOrtega commented
Te respondo tus dudas

2)
Si la longitud de self.card_list es par (es decir, el residuo de la división por 2 es 0), se asigna a la variable cards_dropped la mitad de la longitud de la lista (len(self.card_list) / 2). Esto implica que se deben descartar exactamente la mitad de los cromos.

Si la longitud de self.card_list es impar (el residuo de la división por 2 es 1), se asigna a la variable cards_dropped la mitad de la longitud de la lista más 0.5 ((len(self.card_list) / 2) + 0.5). Esto significa que se descarta la mitad de las cartas y se agrega un cromo adicional. 

Esto es asi ya que un juego de 5 cromos dropea 3, uno de 10 dropea 5, uno de 7 dropea 4.

3) Entiendo, pero es el 85% que se lleva el usuario, por lo tanto deberia multiplicarse por 0.85.], coloco esto y hago la pull request

2023-05-19 17:49 UTC, LucianoOrtega commented
Che se me ocurrió una idea. ¿Qué te parece si agrego una opción de ingresar el precio máximo de los juegos que deseas analizar? Pondría esta opción antes del menú de omitir los juegos que ya están comprados. De esta manera, se puede filtrar los juegos según tu presupuesto antes de realizar el análisis. Sería una forma conveniente de personalizar aún más los resultados.

2023-05-19 21:43 UTC, enzosanchezc commented
Siguiendo el hilo de los comentarios más arriba, claro, es eso lo que hace la lógica actual, el operador // hace la división y descarta el resto, por lo que siempre retorna un entero. Si un juego tiene 7 cromos dropea 3, por eso está bien que redondee para abajo. La única excepción son los juegos de 5 cromos, que dropean 3.

Con respecto al porcentaje que se queda el usuario, tenés fuente? Porque no encontré nada oficial, ese número actual es empírico. Igual capaz que cambio en estos 3 años, voy a chequearlo.

Respondiendo a este último comentario, me parece buena idea, tenía pensado agregarlo en algún momento, pero sería preferible en el archivo de configuración del usuario, porque si bien es algo de preferencia personal, no es un parámetro que se vaya a estar variando todo el tiempo. Capaz estaría bueno que te pregunte en la primera ejecución y después no pregunte más.

2023-05-20 15:06 UTC, enzosanchezc requested changes
Ahí dejé los comentarios en el código

2023-05-20 15:06 UTC, enzosanchezc commented on source/classes.py
> +            cards_dropped = (len(self.card_list) / 2) + 0.5
Estos 2 if's se podrían evitar usando la función ceil de la biblioteca math. Además no es conveniente que el número quede como float en vez de int. Igualmente, como te decía, Steam redondea para abajo al dropear cromos, si por ejemplo un juego tiene 11 cromos, va a dropear 5. La única excepción es cuando tiene 5 cromos, que dropea 3.

2023-05-20 15:06 UTC, enzosanchezc commented on source/classes.py
> +            self.med_profit = round(((median_price * cards_dropped * 0.85 - (self.price))), 3)
En base al último comentario que mandé, ya corroboré que el número actual está bien. Otra cosa que no había notado es que con la fórmula actual, el resultado da en unidades relativo al precio del juego. Con este cambio, la unidad quedaría en pesos, que no es la idea.

2023-05-21 20:48 UTC, LucianoOrtega commented on source/classes.py
> +            self.med_profit = round(((median_price * cards_dropped * 0.85 - (self.price))), 3)
No entendí, que es lo que hace que la unidad quede en pesos?

2023-05-21 20:52 UTC, LucianoOrtega commented on source/classes.py
> +            cards_dropped = (len(self.card_list) / 2) + 0.5
Tenes razón, pero hay algo que me dejo en duda, si un juego tiene 9 cromos por ejemplo, esto dividido dos da 4.5, esto alteraría los retornos final ya que se esta contando la mitad de un cromo.
Esto es asi?

2023-05-21 21:49 UTC, LucianoOrtega commented
Ahí hice una nueva commit, fíjate como quedo.

2023-05-22 22:46 UTC, enzosanchezc commented on source/classes.py
> +            self.med_profit = round(((median_price * cards_dropped * 0.85 - (self.price))), 3)
`Precio * unidades * constante adimensional - precio` te da en pesos. En el código actual te da un valor adimensional

2023-05-22 22:49 UTC, enzosanchezc commented
Lo de max_price deberíamos verlo despues en otro pull request aparte, porque son muchos cambios juntos. Además cada variable que intentes leer del archivo users.json debería tener su propio bloque try/except para poder determinar qué parámetro no existe. 

Otro punto que me di cuenta es que, si bien hiciste que no sea necesario usar webAPIKey, aún falta remover un par de condicionales del resto del programa, por ejemplo cuando te pregunta si queres skipear los juegos de tu biblioteca, ahi se fija si existe la key. Igualmente no hay problema con eso, si queres yo me fijo de sacarlo porque hay que removerlo de la clase User.

En este pull request lo que debería ir son el cambio de "medio" por "promedio" y la obtención de los juegos del usuario sin webAPIKey.

2023-05-23 19:23 UTC, LucianoOrtega commented
Dale dale, dejo esas 2 dos cosas, déjame ver como hago.

2023-05-23 19:26 UTC, closed without merging